require 'rails_helper'

describe 'Items API Business Analysis' do
  before(:each) do
    Transaction.destroy_all
    InvoiceItem.destroy_all
    Item.destroy_all
    Invoice.destroy_all
    Merchant.destroy_all
    Customer.destroy_all

    @item1, @item2, @item3, item4, item5, @item6, item7 = create_list(:item, 7, unit_price: 500)
    create_list(:invoice, 3).each do |invoice|
      create(:invoice_item, invoice: invoice, item: @item1, quantity: 1, unit_price: 500)
      create(:transaction, invoice: invoice)
    end

    @invoices = create_list(:invoice, 5).each do |invoice|
      create(:invoice_item, invoice: invoice, item: @item2, quantity: 1, unit_price: 500)
      create(:transaction, invoice: invoice)
    end

    create_list(:invoice, 2).each do |invoice|
      create(:invoice_item, invoice: invoice, item: @item3, quantity: 1, unit_price: 500)
      create(:transaction, invoice: invoice)
    end

    create_list(:invoice, 4).each do |invoice|
      create(:invoice_item, invoice: invoice, item: item4, quantity: 1, unit_price: 500)
      create(:transaction, invoice: invoice)
    end

    create_list(:invoice, 1).each do |invoice|
      create(:invoice_item, invoice: invoice, item: item5, quantity: 1, unit_price: 500)
      create(:transaction, invoice: invoice)
    end

    create_list(:invoice, 7).each do |invoice|
      create(:invoice_item, invoice: invoice, item: @item6, quantity: 1, unit_price: 500)
      create(:transaction, invoice: invoice)
    end

    create_list(:invoice, 4).each do |invoice|
      create(:invoice_item, invoice: invoice, item: item7, quantity: 1, unit_price: 500)
      create(:transaction, invoice: invoice)
    end
  end

  it 'returns the top (quantity) items by total revenue generated' do
    get api_v1_items_most_revenue_path(quantity: 5)

    results = JSON.parse(response.body)['data']

    expect(response).to be_successful
    expect(results.count).to eq(5)

    expect(results.first['attributes']['id']).to eq(@item6.id)
    expect(results.last['attributes']['id']).to eq(@item1.id)
  end

  it 'returns the top (quantity) items by total number sold' do
    get api_v1_items_most_revenue_path(quantity: 6)

    results = JSON.parse(response.body)['data']

    expect(response).to be_successful
    expect(results.count).to eq(6)

    expect(results.first['attributes']['id']).to eq(@item6.id)
    expect(results.last['attributes']['id']).to eq(@item3.id)
  end

  it 'returns the date with the most revenue generated by the item' do
    @invoices[0].created_at = "2019-05-01"
    @invoices[1].created_at = "2019-05-02"
    @invoices[2].created_at = "2019-04-30"
    @invoices[3].created_at = "2019-05-01"
    @invoices[4].created_at = "2019-05-02"

    @invoices.each{|invoice| invoice.save}

    get "/api/v1/items/#{@item2.id}/best_day"

    result = JSON.parse(response.body)['data']

    expect(response).to be_successful
    expect(result['attributes']['best_day']).to eq('2019-05-02')
  end
end
